[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
db_host = db
db_user = odoo
db_password = odoo
admin_passwd = $pbkdf2-sha512$600000$Z4yxdo7xvtfa27u3du7dmw$EnqC.JopdJiDTrKbsQXStJdL2t6Gyc.auEJU/N5cNt4s/Vdv1ceBIIy/IMWipNmFy7zlilQJn/9I2Nuz2fX4Ng

